show_downloads: true
google_analytics:
theme: jekyll-theme-modernist
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme
title: [JellyBelly's Portfolio of Cybersecurity Projects]
description: [To showcase my super epic cyber skills to my future employer]
